name: guttermouth
services:
  base:
    build:
      context: .
      dockerfile: ./base.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    volumes:
      - ../base:/home
volumes:
  guttermouth:
